import { StyleSheet } from "@react-pdf/renderer";

export const relatorioPdfStyles = StyleSheet.create({
  page: {
    paddingTop: 32,
    paddingRight: 32,
    paddingBottom: 124,
    paddingLeft: 32,
    fontFamily: "Helvetica",
    fontSize: 9,
    color: "#1F2937",
    backgroundColor: "#FFFFFF",
  },
  pageExecutive: {
    paddingTop: 26,
    paddingRight: 30,
    paddingBottom: 58,
    paddingLeft: 30,
    fontSize: 8,
  },
  header: {
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E1D4F0",
    borderBottomStyle: "solid",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 16,
  },
  headerExecutive: {
    paddingBottom: 10,
    gap: 10,
  },
  clinicInfo: {
    flexDirection: "row",
    gap: 12,
    flex: 1,
  },
  logoBox: {
    width: 54,
    height: 54,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E1D4F0",
    backgroundColor: "#F3EAF8",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  logoBoxExecutive: {
    width: 42,
    height: 42,
    borderRadius: 10,
  },
  logoImage: {
    width: 54,
    height: 54,
    objectFit: "cover",
  },
  logoImageExecutive: {
    width: 42,
    height: 42,
  },
  logoFallback: {
    color: "#9F64AF",
    fontSize: 18,
    fontWeight: 700,
  },
  clinicTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "#111827",
    marginBottom: 3,
  },
  clinicTitleExecutive: {
    fontSize: 12,
    marginBottom: 2,
  },
  clinicText: {
    fontSize: 8,
    color: "#4B5563",
    marginBottom: 2,
  },
  clinicTextExecutive: {
    fontSize: 7,
    marginBottom: 1,
  },
  reportIntro: {
    paddingVertical: 18,
  },
  reportIntroExecutive: {
    paddingTop: 12,
    paddingBottom: 10,
  },
  eyebrow: {
    fontSize: 8,
    color: "#9F64AF",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  reportTitle: {
    fontSize: 18,
    color: "#111827",
    fontWeight: 700,
    marginBottom: 6,
  },
  reportTitleExecutive: {
    fontSize: 15,
    marginBottom: 4,
  },
  filterText: {
    fontSize: 9,
    color: "#4B5563",
  },
  section: {
    marginBottom: 16,
  },
  sectionExecutive: {
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 11,
    color: "#111827",
    fontWeight: 700,
    marginBottom: 8,
  },
  sectionTitleExecutive: {
    fontSize: 9,
    marginBottom: 5,
  },
  compactTable: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderStyle: "solid",
  },
  compactTableHeader: {
    flexDirection: "row",
    backgroundColor: "#F8F3FB",
    borderBottomWidth: 1,
    borderBottomColor: "#E1D4F0",
    borderBottomStyle: "solid",
  },
  compactTableRow: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
    borderTopStyle: "solid",
  },
  compactTableCellHeader: {
    flex: 1,
    paddingTop: 4,
    paddingRight: 5,
    paddingBottom: 4,
    paddingLeft: 5,
    fontSize: 7,
    color: "#6F3D7D",
    fontWeight: 700,
  },
  compactTableCell: {
    flex: 1,
    paddingTop: 4,
    paddingRight: 5,
    paddingBottom: 4,
    paddingLeft: 5,
    fontSize: 7,
    color: "#374151",
  },
  summaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  summaryCard: {
    width: "32%",
    minHeight: 44,
    borderWidth: 1,
    borderColor: "#E1D4F0",
    borderStyle: "solid",
    borderRadius: 10,
    backgroundColor: "#FBF7FF",
    padding: 8,
  },
  summaryLabel: {
    fontSize: 7,
    color: "#6F3D7D",
    marginBottom: 4,
    textTransform: "uppercase",
  },
  summaryValue: {
    fontSize: 11,
    color: "#111827",
    fontWeight: 700,
  },
  table: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderStyle: "solid",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#F3EAF8",
  },
  tableRow: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    borderTopStyle: "solid",
  },
  tableCellHeader: {
    flex: 1,
    padding: 6,
    fontSize: 7,
    color: "#6F3D7D",
    fontWeight: 700,
  },
  tableCell: {
    flex: 1,
    padding: 6,
    fontSize: 7,
    color: "#374151",
  },
  empty: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderStyle: "dashed",
    borderRadius: 8,
    padding: 16,
    textAlign: "center",
    color: "#6B7280",
  },
  emptyExecutive: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderStyle: "solid",
    borderRadius: 6,
    paddingTop: 7,
    paddingRight: 8,
    paddingBottom: 7,
    paddingLeft: 8,
    color: "#6B7280",
    fontSize: 7,
  },
  executiveSignatureBlock: {
    position: "absolute",
    right: 30,
    bottom: 38,
    width: 150,
    alignItems: "center",
  },
  executiveSignature: {
    width: 92,
    height: 24,
    objectFit: "contain",
    marginBottom: 2,
  },
  executiveSignaturePlaceholder: {
    width: 118,
    height: 12,
    marginBottom: 3,
    borderBottomWidth: 1,
    borderBottomColor: "#D1D5DB",
    borderBottomStyle: "solid",
  },
  executiveSignatureLine: {
    width: 118,
    borderBottomWidth: 1,
    borderBottomColor: "#D1D5DB",
    borderBottomStyle: "solid",
    marginBottom: 3,
  },
  executiveSignatureName: {
    fontSize: 7,
    color: "#374151",
    fontWeight: 700,
    textAlign: "center",
  },
  executiveSignatureMeta: {
    fontSize: 7,
    color: "#6B7280",
    textAlign: "center",
  },
  signature: {
    width: 150,
    height: 52,
    objectFit: "contain",
    marginTop: 12,
    marginBottom: 5,
    alignSelf: "center",
  },
  signaturePlaceholder: {
    width: 150,
    height: 34,
    marginTop: 14,
    marginBottom: 7,
    borderBottomWidth: 1,
    borderBottomColor: "#D1D5DB",
    borderBottomStyle: "solid",
    alignSelf: "center",
  },
  footer: {
    position: "absolute",
    left: 32,
    right: 32,
    bottom: 18,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#E1D4F0",
    borderTopStyle: "solid",
    alignItems: "center",
  },
  footerExecutive: {
    position: "absolute",
    left: 30,
    right: 30,
    bottom: 14,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: "#E1D4F0",
    borderTopStyle: "solid",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  footerTextExecutive: {
    fontSize: 6,
    color: "#6B7280",
  },
  footerTextExecutiveRight: {
    fontSize: 6,
    color: "#6B7280",
    textAlign: "right",
  },
  footerTitle: {
    textAlign: "center",
    fontSize: 8,
    fontWeight: 700,
    color: "#6F3D7D",
    marginBottom: 3,
  },
  footerLine: {
    maxWidth: 500,
    textAlign: "center",
    fontSize: 7,
    color: "#6B7280",
    marginBottom: 2,
  },
  crpLine: {
    textAlign: "center",
    fontSize: 8,
    color: "#374151",
    fontWeight: 700,
  },
});
